### ISSUE TITLE
Some questions about training

### ISSUE THREAD

**Issue by chi8411** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#7]
Hi, 
I encountered this problem when I wanted to train.
But my test is executable.

KeyError: 'Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py",$
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rvl/dockerData/Ying_Chi/Simultaneous-Traffic-Sign-Detection-and-C$
    boxes = self.annotation_dir.get_boxes(image_fn.split(\'/\')[-1])
  File "/home/rvl/dockerData/Ying_Chi/Simultaneous-Traffic-Sign-Detection-and-C$
    return self.ann_dict[fn]
KeyError: \'19566.jpg\'\n'

Thank you.

**Comment by CJHMPower** [comment]
Hi, 
The dataset consists both images and annotation json file. If you want to train with your own dataset. You must write your own annotation file based on the same format with the provided json file.

**Comment by chi8411** [comment]
Hi,
But I used your data and have the same problem.

**Comment by chi8411** [comment]
Traceback (most recent call last):
  File "train.py", line 150, in <module>
    train(epoch)
  File "train.py", line 78, in train
    for batch_idx, (inputs, loc_targets, cls_targets) in enumerate(trainloader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n
    samples = collate_fn([dataset[i] for i in batch_indices])\n
  File "/home/rvl/dockerData/Ying_Chi/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/preprocessing/datasets.py", line 35, in __getitem__\n
    boxes = self.annotation_dir.get_boxes(image_fn.split(\'/\')[-1])\n
  File "/home/rvl/dockerData/Ying_Chi/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/preprocessing/annotations.py", line 38, in get_boxes\n
    print(self.ann_dict[fn])\n
KeyError: \'61204_0_1.jpg\'\n'
